# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from quant.v1 import api_pb2 as quant_dot_v1_dot_api__pb2


class TaskServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTasks = channel.unary_unary(
                '/quant.v1.TaskService/ListTasks',
                request_serializer=quant_dot_v1_dot_api__pb2.ListTasksRequest.SerializeToString,
                response_deserializer=quant_dot_v1_dot_api__pb2.ListTasksResponse.FromString,
                _registered_method=True)
        self.GetTask = channel.unary_unary(
                '/quant.v1.TaskService/GetTask',
                request_serializer=quant_dot_v1_dot_api__pb2.GetTaskRequest.SerializeToString,
                response_deserializer=quant_dot_v1_dot_api__pb2.Task.FromString,
                _registered_method=True)
        self.RetryTask = channel.unary_unary(
                '/quant.v1.TaskService/RetryTask',
                request_serializer=quant_dot_v1_dot_api__pb2.RetryTaskRequest.SerializeToString,
                response_deserializer=quant_dot_v1_dot_api__pb2.RetryTaskResponse.FromString,
                _registered_method=True)


class TaskServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetryTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTasks,
                    request_deserializer=quant_dot_v1_dot_api__pb2.ListTasksRequest.FromString,
                    response_serializer=quant_dot_v1_dot_api__pb2.ListTasksResponse.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=quant_dot_v1_dot_api__pb2.GetTaskRequest.FromString,
                    response_serializer=quant_dot_v1_dot_api__pb2.Task.SerializeToString,
            ),
            'RetryTask': grpc.unary_unary_rpc_method_handler(
                    servicer.RetryTask,
                    request_deserializer=quant_dot_v1_dot_api__pb2.RetryTaskRequest.FromString,
                    response_serializer=quant_dot_v1_dot_api__pb2.RetryTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'quant.v1.TaskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('quant.v1.TaskService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quant.v1.TaskService/ListTasks',
            quant_dot_v1_dot_api__pb2.ListTasksRequest.SerializeToString,
            quant_dot_v1_dot_api__pb2.ListTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quant.v1.TaskService/GetTask',
            quant_dot_v1_dot_api__pb2.GetTaskRequest.SerializeToString,
            quant_dot_v1_dot_api__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetryTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quant.v1.TaskService/RetryTask',
            quant_dot_v1_dot_api__pb2.RetryTaskRequest.SerializeToString,
            quant_dot_v1_dot_api__pb2.RetryTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WatchlistServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListWatchlist = channel.unary_unary(
                '/quant.v1.WatchlistService/ListWatchlist',
                request_serializer=quant_dot_v1_dot_api__pb2.ListWatchlistRequest.SerializeToString,
                response_deserializer=quant_dot_v1_dot_api__pb2.ListWatchlistResponse.FromString,
                _registered_method=True)
        self.AddWatchlistItem = channel.unary_unary(
                '/quant.v1.WatchlistService/AddWatchlistItem',
                request_serializer=quant_dot_v1_dot_api__pb2.AddWatchlistItemRequest.SerializeToString,
                response_deserializer=quant_dot_v1_dot_api__pb2.WatchlistItem.FromString,
                _registered_method=True)
        self.RemoveWatchlistItem = channel.unary_unary(
                '/quant.v1.WatchlistService/RemoveWatchlistItem',
                request_serializer=quant_dot_v1_dot_api__pb2.RemoveWatchlistItemRequest.SerializeToString,
                response_deserializer=quant_dot_v1_dot_api__pb2.WatchlistItem.FromString,
                _registered_method=True)


class WatchlistServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListWatchlist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddWatchlistItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveWatchlistItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WatchlistServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListWatchlist': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWatchlist,
                    request_deserializer=quant_dot_v1_dot_api__pb2.ListWatchlistRequest.FromString,
                    response_serializer=quant_dot_v1_dot_api__pb2.ListWatchlistResponse.SerializeToString,
            ),
            'AddWatchlistItem': grpc.unary_unary_rpc_method_handler(
                    servicer.AddWatchlistItem,
                    request_deserializer=quant_dot_v1_dot_api__pb2.AddWatchlistItemRequest.FromString,
                    response_serializer=quant_dot_v1_dot_api__pb2.WatchlistItem.SerializeToString,
            ),
            'RemoveWatchlistItem': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveWatchlistItem,
                    request_deserializer=quant_dot_v1_dot_api__pb2.RemoveWatchlistItemRequest.FromString,
                    response_serializer=quant_dot_v1_dot_api__pb2.WatchlistItem.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'quant.v1.WatchlistService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('quant.v1.WatchlistService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WatchlistService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListWatchlist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quant.v1.WatchlistService/ListWatchlist',
            quant_dot_v1_dot_api__pb2.ListWatchlistRequest.SerializeToString,
            quant_dot_v1_dot_api__pb2.ListWatchlistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddWatchlistItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quant.v1.WatchlistService/AddWatchlistItem',
            quant_dot_v1_dot_api__pb2.AddWatchlistItemRequest.SerializeToString,
            quant_dot_v1_dot_api__pb2.WatchlistItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveWatchlistItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quant.v1.WatchlistService/RemoveWatchlistItem',
            quant_dot_v1_dot_api__pb2.RemoveWatchlistItemRequest.SerializeToString,
            quant_dot_v1_dot_api__pb2.WatchlistItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PortfolioServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTrade = channel.unary_unary(
                '/quant.v1.PortfolioService/CreateTrade',
                request_serializer=quant_dot_v1_dot_api__pb2.CreateTradeRequest.SerializeToString,
                response_deserializer=quant_dot_v1_dot_api__pb2.Trade.FromString,
                _registered_method=True)
        self.ListTrades = channel.unary_unary(
                '/quant.v1.PortfolioService/ListTrades',
                request_serializer=quant_dot_v1_dot_api__pb2.ListTradesRequest.SerializeToString,
                response_deserializer=quant_dot_v1_dot_api__pb2.ListTradesResponse.FromString,
                _registered_method=True)
        self.CreateDividend = channel.unary_unary(
                '/quant.v1.PortfolioService/CreateDividend',
                request_serializer=quant_dot_v1_dot_api__pb2.CreateDividendRequest.SerializeToString,
                response_deserializer=quant_dot_v1_dot_api__pb2.Dividend.FromString,
                _registered_method=True)
        self.ListDividends = channel.unary_unary(
                '/quant.v1.PortfolioService/ListDividends',
                request_serializer=quant_dot_v1_dot_api__pb2.ListDividendsRequest.SerializeToString,
                response_deserializer=quant_dot_v1_dot_api__pb2.ListDividendsResponse.FromString,
                _registered_method=True)
        self.CreateCashFlow = channel.unary_unary(
                '/quant.v1.PortfolioService/CreateCashFlow',
                request_serializer=quant_dot_v1_dot_api__pb2.CreateCashFlowRequest.SerializeToString,
                response_deserializer=quant_dot_v1_dot_api__pb2.CashFlow.FromString,
                _registered_method=True)
        self.ListCashFlows = channel.unary_unary(
                '/quant.v1.PortfolioService/ListCashFlows',
                request_serializer=quant_dot_v1_dot_api__pb2.ListCashFlowsRequest.SerializeToString,
                response_deserializer=quant_dot_v1_dot_api__pb2.ListCashFlowsResponse.FromString,
                _registered_method=True)
        self.ListPositions = channel.unary_unary(
                '/quant.v1.PortfolioService/ListPositions',
                request_serializer=quant_dot_v1_dot_api__pb2.Empty.SerializeToString,
                response_deserializer=quant_dot_v1_dot_api__pb2.ListPositionsResponse.FromString,
                _registered_method=True)
        self.CreateValuation = channel.unary_unary(
                '/quant.v1.PortfolioService/CreateValuation',
                request_serializer=quant_dot_v1_dot_api__pb2.CreateValuationRequest.SerializeToString,
                response_deserializer=quant_dot_v1_dot_api__pb2.Valuation.FromString,
                _registered_method=True)
        self.ListValuations = channel.unary_unary(
                '/quant.v1.PortfolioService/ListValuations',
                request_serializer=quant_dot_v1_dot_api__pb2.ListValuationsRequest.SerializeToString,
                response_deserializer=quant_dot_v1_dot_api__pb2.ListValuationsResponse.FromString,
                _registered_method=True)
        self.GetAssets = channel.unary_unary(
                '/quant.v1.PortfolioService/GetAssets',
                request_serializer=quant_dot_v1_dot_api__pb2.GetAssetsRequest.SerializeToString,
                response_deserializer=quant_dot_v1_dot_api__pb2.GetAssetsResponse.FromString,
                _registered_method=True)
        self.GetAnnualReview = channel.unary_unary(
                '/quant.v1.PortfolioService/GetAnnualReview',
                request_serializer=quant_dot_v1_dot_api__pb2.GetAnnualReviewRequest.SerializeToString,
                response_deserializer=quant_dot_v1_dot_api__pb2.AnnualReview.FromString,
                _registered_method=True)


class PortfolioServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateTrade(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTrades(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateDividend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDividends(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCashFlow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCashFlows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPositions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateValuation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListValuations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAssets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAnnualReview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PortfolioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTrade': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTrade,
                    request_deserializer=quant_dot_v1_dot_api__pb2.CreateTradeRequest.FromString,
                    response_serializer=quant_dot_v1_dot_api__pb2.Trade.SerializeToString,
            ),
            'ListTrades': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTrades,
                    request_deserializer=quant_dot_v1_dot_api__pb2.ListTradesRequest.FromString,
                    response_serializer=quant_dot_v1_dot_api__pb2.ListTradesResponse.SerializeToString,
            ),
            'CreateDividend': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDividend,
                    request_deserializer=quant_dot_v1_dot_api__pb2.CreateDividendRequest.FromString,
                    response_serializer=quant_dot_v1_dot_api__pb2.Dividend.SerializeToString,
            ),
            'ListDividends': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDividends,
                    request_deserializer=quant_dot_v1_dot_api__pb2.ListDividendsRequest.FromString,
                    response_serializer=quant_dot_v1_dot_api__pb2.ListDividendsResponse.SerializeToString,
            ),
            'CreateCashFlow': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCashFlow,
                    request_deserializer=quant_dot_v1_dot_api__pb2.CreateCashFlowRequest.FromString,
                    response_serializer=quant_dot_v1_dot_api__pb2.CashFlow.SerializeToString,
            ),
            'ListCashFlows': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCashFlows,
                    request_deserializer=quant_dot_v1_dot_api__pb2.ListCashFlowsRequest.FromString,
                    response_serializer=quant_dot_v1_dot_api__pb2.ListCashFlowsResponse.SerializeToString,
            ),
            'ListPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPositions,
                    request_deserializer=quant_dot_v1_dot_api__pb2.Empty.FromString,
                    response_serializer=quant_dot_v1_dot_api__pb2.ListPositionsResponse.SerializeToString,
            ),
            'CreateValuation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateValuation,
                    request_deserializer=quant_dot_v1_dot_api__pb2.CreateValuationRequest.FromString,
                    response_serializer=quant_dot_v1_dot_api__pb2.Valuation.SerializeToString,
            ),
            'ListValuations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListValuations,
                    request_deserializer=quant_dot_v1_dot_api__pb2.ListValuationsRequest.FromString,
                    response_serializer=quant_dot_v1_dot_api__pb2.ListValuationsResponse.SerializeToString,
            ),
            'GetAssets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAssets,
                    request_deserializer=quant_dot_v1_dot_api__pb2.GetAssetsRequest.FromString,
                    response_serializer=quant_dot_v1_dot_api__pb2.GetAssetsResponse.SerializeToString,
            ),
            'GetAnnualReview': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnnualReview,
                    request_deserializer=quant_dot_v1_dot_api__pb2.GetAnnualReviewRequest.FromString,
                    response_serializer=quant_dot_v1_dot_api__pb2.AnnualReview.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'quant.v1.PortfolioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('quant.v1.PortfolioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PortfolioService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTrade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quant.v1.PortfolioService/CreateTrade',
            quant_dot_v1_dot_api__pb2.CreateTradeRequest.SerializeToString,
            quant_dot_v1_dot_api__pb2.Trade.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTrades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quant.v1.PortfolioService/ListTrades',
            quant_dot_v1_dot_api__pb2.ListTradesRequest.SerializeToString,
            quant_dot_v1_dot_api__pb2.ListTradesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateDividend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quant.v1.PortfolioService/CreateDividend',
            quant_dot_v1_dot_api__pb2.CreateDividendRequest.SerializeToString,
            quant_dot_v1_dot_api__pb2.Dividend.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDividends(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quant.v1.PortfolioService/ListDividends',
            quant_dot_v1_dot_api__pb2.ListDividendsRequest.SerializeToString,
            quant_dot_v1_dot_api__pb2.ListDividendsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCashFlow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quant.v1.PortfolioService/CreateCashFlow',
            quant_dot_v1_dot_api__pb2.CreateCashFlowRequest.SerializeToString,
            quant_dot_v1_dot_api__pb2.CashFlow.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCashFlows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quant.v1.PortfolioService/ListCashFlows',
            quant_dot_v1_dot_api__pb2.ListCashFlowsRequest.SerializeToString,
            quant_dot_v1_dot_api__pb2.ListCashFlowsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quant.v1.PortfolioService/ListPositions',
            quant_dot_v1_dot_api__pb2.Empty.SerializeToString,
            quant_dot_v1_dot_api__pb2.ListPositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateValuation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quant.v1.PortfolioService/CreateValuation',
            quant_dot_v1_dot_api__pb2.CreateValuationRequest.SerializeToString,
            quant_dot_v1_dot_api__pb2.Valuation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListValuations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quant.v1.PortfolioService/ListValuations',
            quant_dot_v1_dot_api__pb2.ListValuationsRequest.SerializeToString,
            quant_dot_v1_dot_api__pb2.ListValuationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAssets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quant.v1.PortfolioService/GetAssets',
            quant_dot_v1_dot_api__pb2.GetAssetsRequest.SerializeToString,
            quant_dot_v1_dot_api__pb2.GetAssetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAnnualReview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quant.v1.PortfolioService/GetAnnualReview',
            quant_dot_v1_dot_api__pb2.GetAnnualReviewRequest.SerializeToString,
            quant_dot_v1_dot_api__pb2.AnnualReview.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DataServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListStocks = channel.unary_unary(
                '/quant.v1.DataService/ListStocks',
                request_serializer=quant_dot_v1_dot_api__pb2.ListStocksRequest.SerializeToString,
                response_deserializer=quant_dot_v1_dot_api__pb2.ListStocksResponse.FromString,
                _registered_method=True)
        self.ListDailyBars = channel.unary_unary(
                '/quant.v1.DataService/ListDailyBars',
                request_serializer=quant_dot_v1_dot_api__pb2.ListDailyBarsRequest.SerializeToString,
                response_deserializer=quant_dot_v1_dot_api__pb2.ListDailyBarsResponse.FromString,
                _registered_method=True)
        self.SyncStock = channel.unary_unary(
                '/quant.v1.DataService/SyncStock',
                request_serializer=quant_dot_v1_dot_api__pb2.SyncStockRequest.SerializeToString,
                response_deserializer=quant_dot_v1_dot_api__pb2.Task.FromString,
                _registered_method=True)
        self.ListDataTasks = channel.unary_unary(
                '/quant.v1.DataService/ListDataTasks',
                request_serializer=quant_dot_v1_dot_api__pb2.ListDataTasksRequest.SerializeToString,
                response_deserializer=quant_dot_v1_dot_api__pb2.ListDataTasksResponse.FromString,
                _registered_method=True)
        self.ListStockPool = channel.unary_unary(
                '/quant.v1.DataService/ListStockPool',
                request_serializer=quant_dot_v1_dot_api__pb2.ListStockPoolRequest.SerializeToString,
                response_deserializer=quant_dot_v1_dot_api__pb2.ListStockPoolResponse.FromString,
                _registered_method=True)
        self.UpsertStockPoolItem = channel.unary_unary(
                '/quant.v1.DataService/UpsertStockPoolItem',
                request_serializer=quant_dot_v1_dot_api__pb2.UpsertStockPoolItemRequest.SerializeToString,
                response_deserializer=quant_dot_v1_dot_api__pb2.StockPoolItem.FromString,
                _registered_method=True)


class DataServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListStocks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDailyBars(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDataTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStockPool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertStockPoolItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListStocks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStocks,
                    request_deserializer=quant_dot_v1_dot_api__pb2.ListStocksRequest.FromString,
                    response_serializer=quant_dot_v1_dot_api__pb2.ListStocksResponse.SerializeToString,
            ),
            'ListDailyBars': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDailyBars,
                    request_deserializer=quant_dot_v1_dot_api__pb2.ListDailyBarsRequest.FromString,
                    response_serializer=quant_dot_v1_dot_api__pb2.ListDailyBarsResponse.SerializeToString,
            ),
            'SyncStock': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncStock,
                    request_deserializer=quant_dot_v1_dot_api__pb2.SyncStockRequest.FromString,
                    response_serializer=quant_dot_v1_dot_api__pb2.Task.SerializeToString,
            ),
            'ListDataTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDataTasks,
                    request_deserializer=quant_dot_v1_dot_api__pb2.ListDataTasksRequest.FromString,
                    response_serializer=quant_dot_v1_dot_api__pb2.ListDataTasksResponse.SerializeToString,
            ),
            'ListStockPool': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStockPool,
                    request_deserializer=quant_dot_v1_dot_api__pb2.ListStockPoolRequest.FromString,
                    response_serializer=quant_dot_v1_dot_api__pb2.ListStockPoolResponse.SerializeToString,
            ),
            'UpsertStockPoolItem': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertStockPoolItem,
                    request_deserializer=quant_dot_v1_dot_api__pb2.UpsertStockPoolItemRequest.FromString,
                    response_serializer=quant_dot_v1_dot_api__pb2.StockPoolItem.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'quant.v1.DataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('quant.v1.DataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListStocks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quant.v1.DataService/ListStocks',
            quant_dot_v1_dot_api__pb2.ListStocksRequest.SerializeToString,
            quant_dot_v1_dot_api__pb2.ListStocksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDailyBars(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quant.v1.DataService/ListDailyBars',
            quant_dot_v1_dot_api__pb2.ListDailyBarsRequest.SerializeToString,
            quant_dot_v1_dot_api__pb2.ListDailyBarsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quant.v1.DataService/SyncStock',
            quant_dot_v1_dot_api__pb2.SyncStockRequest.SerializeToString,
            quant_dot_v1_dot_api__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDataTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quant.v1.DataService/ListDataTasks',
            quant_dot_v1_dot_api__pb2.ListDataTasksRequest.SerializeToString,
            quant_dot_v1_dot_api__pb2.ListDataTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStockPool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quant.v1.DataService/ListStockPool',
            quant_dot_v1_dot_api__pb2.ListStockPoolRequest.SerializeToString,
            quant_dot_v1_dot_api__pb2.ListStockPoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertStockPoolItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quant.v1.DataService/UpsertStockPoolItem',
            quant_dot_v1_dot_api__pb2.UpsertStockPoolItemRequest.SerializeToString,
            quant_dot_v1_dot_api__pb2.StockPoolItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AnalysisServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunAnalysis = channel.unary_unary(
                '/quant.v1.AnalysisService/RunAnalysis',
                request_serializer=quant_dot_v1_dot_api__pb2.RunAnalysisRequest.SerializeToString,
                response_deserializer=quant_dot_v1_dot_api__pb2.Task.FromString,
                _registered_method=True)
        self.PredictOnDemand = channel.unary_unary(
                '/quant.v1.AnalysisService/PredictOnDemand',
                request_serializer=quant_dot_v1_dot_api__pb2.PredictOnDemandRequest.SerializeToString,
                response_deserializer=quant_dot_v1_dot_api__pb2.Prediction.FromString,
                _registered_method=True)
        self.ListPredictions = channel.unary_unary(
                '/quant.v1.AnalysisService/ListPredictions',
                request_serializer=quant_dot_v1_dot_api__pb2.ListPredictionsRequest.SerializeToString,
                response_deserializer=quant_dot_v1_dot_api__pb2.ListPredictionsResponse.FromString,
                _registered_method=True)


class AnalysisServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RunAnalysis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictOnDemand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPredictions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.RunAnalysis,
                    request_deserializer=quant_dot_v1_dot_api__pb2.RunAnalysisRequest.FromString,
                    response_serializer=quant_dot_v1_dot_api__pb2.Task.SerializeToString,
            ),
            'PredictOnDemand': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictOnDemand,
                    request_deserializer=quant_dot_v1_dot_api__pb2.PredictOnDemandRequest.FromString,
                    response_serializer=quant_dot_v1_dot_api__pb2.Prediction.SerializeToString,
            ),
            'ListPredictions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPredictions,
                    request_deserializer=quant_dot_v1_dot_api__pb2.ListPredictionsRequest.FromString,
                    response_serializer=quant_dot_v1_dot_api__pb2.ListPredictionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'quant.v1.AnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('quant.v1.AnalysisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalysisService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quant.v1.AnalysisService/RunAnalysis',
            quant_dot_v1_dot_api__pb2.RunAnalysisRequest.SerializeToString,
            quant_dot_v1_dot_api__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictOnDemand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quant.v1.AnalysisService/PredictOnDemand',
            quant_dot_v1_dot_api__pb2.PredictOnDemandRequest.SerializeToString,
            quant_dot_v1_dot_api__pb2.Prediction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPredictions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quant.v1.AnalysisService/ListPredictions',
            quant_dot_v1_dot_api__pb2.ListPredictionsRequest.SerializeToString,
            quant_dot_v1_dot_api__pb2.ListPredictionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
