# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: quant/v1/crawler.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'quant/v1/crawler.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16quant/v1/crawler.proto\x12\x08quant.v1\"r\n\x15\x46\x65tchDailyBarsRequest\x12\x1f\n\x0bstock_codes\x18\x01 \x03(\tR\nstockCodes\x12\x1d\n\nstart_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n\x08\x65nd_date\x18\x03 \x01(\tR\x07\x65ndDate\"\xe7\x01\n\x0f\x43leanedDailyBar\x12\x1d\n\nstock_code\x18\x01 \x01(\tR\tstockCode\x12\x16\n\x06market\x18\x02 \x01(\tR\x06market\x12\x1d\n\ntrade_date\x18\x03 \x01(\tR\ttradeDate\x12\x12\n\x04open\x18\x04 \x01(\x01R\x04open\x12\x12\n\x04high\x18\x05 \x01(\x01R\x04high\x12\x10\n\x03low\x18\x06 \x01(\x01R\x03low\x12\x14\n\x05\x63lose\x18\x07 \x01(\x01R\x05\x63lose\x12\x16\n\x06volume\x18\x08 \x01(\x03R\x06volume\x12\x16\n\x06source\x18\t \x01(\tR\x06source\"|\n\x16\x46\x65tchDailyBarsResponse\x12\x1d\n\nstock_code\x18\x01 \x01(\tR\tstockCode\x12-\n\x04\x62\x61rs\x18\x02 \x03(\x0b\x32\x19.quant.v1.CleanedDailyBarR\x04\x62\x61rs\x12\x14\n\x05\x65rror\x18\x03 \x01(\tR\x05\x65rror2g\n\x0e\x43rawlerService\x12U\n\x0e\x46\x65tchDailyBars\x12\x1f.quant.v1.FetchDailyBarsRequest\x1a .quant.v1.FetchDailyBarsResponse0\x01\x42\x93\x01\n\x0c\x63om.quant.v1B\x0c\x43rawlerProtoP\x01Z4github.com/gsxhnd/guanlan/internal/proto/quant/v1;v1\xa2\x02\x03QXX\xaa\x02\x08Quant.V1\xca\x02\x08Quant\\V1\xe2\x02\x14Quant\\V1\\GPBMetadata\xea\x02\tQuant::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quant.v1.crawler_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\014com.quant.v1B\014CrawlerProtoP\001Z4github.com/gsxhnd/guanlan/internal/proto/quant/v1;v1\242\002\003QXX\252\002\010Quant.V1\312\002\010Quant\\V1\342\002\024Quant\\V1\\GPBMetadata\352\002\tQuant::V1'
  _globals['_FETCHDAILYBARSREQUEST']._serialized_start=36
  _globals['_FETCHDAILYBARSREQUEST']._serialized_end=150
  _globals['_CLEANEDDAILYBAR']._serialized_start=153
  _globals['_CLEANEDDAILYBAR']._serialized_end=384
  _globals['_FETCHDAILYBARSRESPONSE']._serialized_start=386
  _globals['_FETCHDAILYBARSRESPONSE']._serialized_end=510
  _globals['_CRAWLERSERVICE']._serialized_start=512
  _globals['_CRAWLERSERVICE']._serialized_end=615
# @@protoc_insertion_point(module_scope)
