# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from quant.v1 import crawler_pb2 as quant_dot_v1_dot_crawler__pb2


class CrawlerServiceStub:
    """CrawlerService is a stateless fetch/clean gRPC API used by cmd/api orchestrator.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchDailyBars = channel.unary_stream(
                '/quant.v1.CrawlerService/FetchDailyBars',
                request_serializer=quant_dot_v1_dot_crawler__pb2.FetchDailyBarsRequest.SerializeToString,
                response_deserializer=quant_dot_v1_dot_crawler__pb2.FetchDailyBarsResponse.FromString,
                _registered_method=True)


class CrawlerServiceServicer:
    """CrawlerService is a stateless fetch/clean gRPC API used by cmd/api orchestrator.
    """

    def FetchDailyBars(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CrawlerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FetchDailyBars': grpc.unary_stream_rpc_method_handler(
                    servicer.FetchDailyBars,
                    request_deserializer=quant_dot_v1_dot_crawler__pb2.FetchDailyBarsRequest.FromString,
                    response_serializer=quant_dot_v1_dot_crawler__pb2.FetchDailyBarsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'quant.v1.CrawlerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('quant.v1.CrawlerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CrawlerService:
    """CrawlerService is a stateless fetch/clean gRPC API used by cmd/api orchestrator.
    """

    @staticmethod
    def FetchDailyBars(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/quant.v1.CrawlerService/FetchDailyBars',
            quant_dot_v1_dot_crawler__pb2.FetchDailyBarsRequest.SerializeToString,
            quant_dot_v1_dot_crawler__pb2.FetchDailyBarsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
