// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: v1/api.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskService_ListTasks_FullMethodName = "/guanlan.v1.TaskService/ListTasks"
	TaskService_GetTask_FullMethodName   = "/guanlan.v1.TaskService/GetTask"
	TaskService_RetryTask_FullMethodName = "/guanlan.v1.TaskService/RetryTask"
)

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskServiceClient interface {
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error)
	RetryTask(ctx context.Context, in *RetryTaskRequest, opts ...grpc.CallOption) (*RetryTaskResponse, error)
}

type taskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskServiceClient(cc grpc.ClientConnInterface) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, TaskService_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, TaskService_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) RetryTask(ctx context.Context, in *RetryTaskRequest, opts ...grpc.CallOption) (*RetryTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetryTaskResponse)
	err := c.cc.Invoke(ctx, TaskService_RetryTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServiceServer is the server API for TaskService service.
// All implementations should embed UnimplementedTaskServiceServer
// for forward compatibility.
type TaskServiceServer interface {
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	GetTask(context.Context, *GetTaskRequest) (*Task, error)
	RetryTask(context.Context, *RetryTaskRequest) (*RetryTaskResponse, error)
}

// UnimplementedTaskServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskServiceServer struct{}

func (UnimplementedTaskServiceServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedTaskServiceServer) GetTask(context.Context, *GetTaskRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedTaskServiceServer) RetryTask(context.Context, *RetryTaskRequest) (*RetryTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryTask not implemented")
}
func (UnimplementedTaskServiceServer) testEmbeddedByValue() {}

// UnsafeTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskServiceServer will
// result in compilation errors.
type UnsafeTaskServiceServer interface {
	mustEmbedUnimplementedTaskServiceServer()
}

func RegisterTaskServiceServer(s grpc.ServiceRegistrar, srv TaskServiceServer) {
	// If the following call panics, it indicates UnimplementedTaskServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskService_ServiceDesc, srv)
}

func _TaskService_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_RetryTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).RetryTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_RetryTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).RetryTask(ctx, req.(*RetryTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskService_ServiceDesc is the grpc.ServiceDesc for TaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "guanlan.v1.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTasks",
			Handler:    _TaskService_ListTasks_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _TaskService_GetTask_Handler,
		},
		{
			MethodName: "RetryTask",
			Handler:    _TaskService_RetryTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/api.proto",
}

const (
	WatchlistService_ListWatchlist_FullMethodName       = "/guanlan.v1.WatchlistService/ListWatchlist"
	WatchlistService_AddWatchlistItem_FullMethodName    = "/guanlan.v1.WatchlistService/AddWatchlistItem"
	WatchlistService_RemoveWatchlistItem_FullMethodName = "/guanlan.v1.WatchlistService/RemoveWatchlistItem"
)

// WatchlistServiceClient is the client API for WatchlistService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WatchlistServiceClient interface {
	ListWatchlist(ctx context.Context, in *ListWatchlistRequest, opts ...grpc.CallOption) (*ListWatchlistResponse, error)
	AddWatchlistItem(ctx context.Context, in *AddWatchlistItemRequest, opts ...grpc.CallOption) (*WatchlistItem, error)
	RemoveWatchlistItem(ctx context.Context, in *RemoveWatchlistItemRequest, opts ...grpc.CallOption) (*WatchlistItem, error)
}

type watchlistServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWatchlistServiceClient(cc grpc.ClientConnInterface) WatchlistServiceClient {
	return &watchlistServiceClient{cc}
}

func (c *watchlistServiceClient) ListWatchlist(ctx context.Context, in *ListWatchlistRequest, opts ...grpc.CallOption) (*ListWatchlistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWatchlistResponse)
	err := c.cc.Invoke(ctx, WatchlistService_ListWatchlist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchlistServiceClient) AddWatchlistItem(ctx context.Context, in *AddWatchlistItemRequest, opts ...grpc.CallOption) (*WatchlistItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WatchlistItem)
	err := c.cc.Invoke(ctx, WatchlistService_AddWatchlistItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchlistServiceClient) RemoveWatchlistItem(ctx context.Context, in *RemoveWatchlistItemRequest, opts ...grpc.CallOption) (*WatchlistItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WatchlistItem)
	err := c.cc.Invoke(ctx, WatchlistService_RemoveWatchlistItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WatchlistServiceServer is the server API for WatchlistService service.
// All implementations should embed UnimplementedWatchlistServiceServer
// for forward compatibility.
type WatchlistServiceServer interface {
	ListWatchlist(context.Context, *ListWatchlistRequest) (*ListWatchlistResponse, error)
	AddWatchlistItem(context.Context, *AddWatchlistItemRequest) (*WatchlistItem, error)
	RemoveWatchlistItem(context.Context, *RemoveWatchlistItemRequest) (*WatchlistItem, error)
}

// UnimplementedWatchlistServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWatchlistServiceServer struct{}

func (UnimplementedWatchlistServiceServer) ListWatchlist(context.Context, *ListWatchlistRequest) (*ListWatchlistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWatchlist not implemented")
}
func (UnimplementedWatchlistServiceServer) AddWatchlistItem(context.Context, *AddWatchlistItemRequest) (*WatchlistItem, error) {
	return nil, status.Error(codes.Unimplemented, "method AddWatchlistItem not implemented")
}
func (UnimplementedWatchlistServiceServer) RemoveWatchlistItem(context.Context, *RemoveWatchlistItemRequest) (*WatchlistItem, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveWatchlistItem not implemented")
}
func (UnimplementedWatchlistServiceServer) testEmbeddedByValue() {}

// UnsafeWatchlistServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WatchlistServiceServer will
// result in compilation errors.
type UnsafeWatchlistServiceServer interface {
	mustEmbedUnimplementedWatchlistServiceServer()
}

func RegisterWatchlistServiceServer(s grpc.ServiceRegistrar, srv WatchlistServiceServer) {
	// If the following call panics, it indicates UnimplementedWatchlistServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WatchlistService_ServiceDesc, srv)
}

func _WatchlistService_ListWatchlist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWatchlistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchlistServiceServer).ListWatchlist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchlistService_ListWatchlist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchlistServiceServer).ListWatchlist(ctx, req.(*ListWatchlistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchlistService_AddWatchlistItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWatchlistItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchlistServiceServer).AddWatchlistItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchlistService_AddWatchlistItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchlistServiceServer).AddWatchlistItem(ctx, req.(*AddWatchlistItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchlistService_RemoveWatchlistItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveWatchlistItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchlistServiceServer).RemoveWatchlistItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchlistService_RemoveWatchlistItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchlistServiceServer).RemoveWatchlistItem(ctx, req.(*RemoveWatchlistItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WatchlistService_ServiceDesc is the grpc.ServiceDesc for WatchlistService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WatchlistService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "guanlan.v1.WatchlistService",
	HandlerType: (*WatchlistServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListWatchlist",
			Handler:    _WatchlistService_ListWatchlist_Handler,
		},
		{
			MethodName: "AddWatchlistItem",
			Handler:    _WatchlistService_AddWatchlistItem_Handler,
		},
		{
			MethodName: "RemoveWatchlistItem",
			Handler:    _WatchlistService_RemoveWatchlistItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/api.proto",
}

const (
	PortfolioService_CreateTrade_FullMethodName     = "/guanlan.v1.PortfolioService/CreateTrade"
	PortfolioService_ListTrades_FullMethodName      = "/guanlan.v1.PortfolioService/ListTrades"
	PortfolioService_CreateDividend_FullMethodName  = "/guanlan.v1.PortfolioService/CreateDividend"
	PortfolioService_ListDividends_FullMethodName   = "/guanlan.v1.PortfolioService/ListDividends"
	PortfolioService_CreateCashFlow_FullMethodName  = "/guanlan.v1.PortfolioService/CreateCashFlow"
	PortfolioService_ListCashFlows_FullMethodName   = "/guanlan.v1.PortfolioService/ListCashFlows"
	PortfolioService_ListPositions_FullMethodName   = "/guanlan.v1.PortfolioService/ListPositions"
	PortfolioService_CreateValuation_FullMethodName = "/guanlan.v1.PortfolioService/CreateValuation"
	PortfolioService_ListValuations_FullMethodName  = "/guanlan.v1.PortfolioService/ListValuations"
	PortfolioService_GetAssets_FullMethodName       = "/guanlan.v1.PortfolioService/GetAssets"
	PortfolioService_GetAnnualReview_FullMethodName = "/guanlan.v1.PortfolioService/GetAnnualReview"
)

// PortfolioServiceClient is the client API for PortfolioService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PortfolioServiceClient interface {
	CreateTrade(ctx context.Context, in *CreateTradeRequest, opts ...grpc.CallOption) (*Trade, error)
	ListTrades(ctx context.Context, in *ListTradesRequest, opts ...grpc.CallOption) (*ListTradesResponse, error)
	CreateDividend(ctx context.Context, in *CreateDividendRequest, opts ...grpc.CallOption) (*Dividend, error)
	ListDividends(ctx context.Context, in *ListDividendsRequest, opts ...grpc.CallOption) (*ListDividendsResponse, error)
	CreateCashFlow(ctx context.Context, in *CreateCashFlowRequest, opts ...grpc.CallOption) (*CashFlow, error)
	ListCashFlows(ctx context.Context, in *ListCashFlowsRequest, opts ...grpc.CallOption) (*ListCashFlowsResponse, error)
	ListPositions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListPositionsResponse, error)
	CreateValuation(ctx context.Context, in *CreateValuationRequest, opts ...grpc.CallOption) (*Valuation, error)
	ListValuations(ctx context.Context, in *ListValuationsRequest, opts ...grpc.CallOption) (*ListValuationsResponse, error)
	GetAssets(ctx context.Context, in *GetAssetsRequest, opts ...grpc.CallOption) (*GetAssetsResponse, error)
	GetAnnualReview(ctx context.Context, in *GetAnnualReviewRequest, opts ...grpc.CallOption) (*AnnualReview, error)
}

type portfolioServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPortfolioServiceClient(cc grpc.ClientConnInterface) PortfolioServiceClient {
	return &portfolioServiceClient{cc}
}

func (c *portfolioServiceClient) CreateTrade(ctx context.Context, in *CreateTradeRequest, opts ...grpc.CallOption) (*Trade, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Trade)
	err := c.cc.Invoke(ctx, PortfolioService_CreateTrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) ListTrades(ctx context.Context, in *ListTradesRequest, opts ...grpc.CallOption) (*ListTradesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTradesResponse)
	err := c.cc.Invoke(ctx, PortfolioService_ListTrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) CreateDividend(ctx context.Context, in *CreateDividendRequest, opts ...grpc.CallOption) (*Dividend, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Dividend)
	err := c.cc.Invoke(ctx, PortfolioService_CreateDividend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) ListDividends(ctx context.Context, in *ListDividendsRequest, opts ...grpc.CallOption) (*ListDividendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDividendsResponse)
	err := c.cc.Invoke(ctx, PortfolioService_ListDividends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) CreateCashFlow(ctx context.Context, in *CreateCashFlowRequest, opts ...grpc.CallOption) (*CashFlow, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CashFlow)
	err := c.cc.Invoke(ctx, PortfolioService_CreateCashFlow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) ListCashFlows(ctx context.Context, in *ListCashFlowsRequest, opts ...grpc.CallOption) (*ListCashFlowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCashFlowsResponse)
	err := c.cc.Invoke(ctx, PortfolioService_ListCashFlows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) ListPositions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListPositionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPositionsResponse)
	err := c.cc.Invoke(ctx, PortfolioService_ListPositions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) CreateValuation(ctx context.Context, in *CreateValuationRequest, opts ...grpc.CallOption) (*Valuation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Valuation)
	err := c.cc.Invoke(ctx, PortfolioService_CreateValuation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) ListValuations(ctx context.Context, in *ListValuationsRequest, opts ...grpc.CallOption) (*ListValuationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListValuationsResponse)
	err := c.cc.Invoke(ctx, PortfolioService_ListValuations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) GetAssets(ctx context.Context, in *GetAssetsRequest, opts ...grpc.CallOption) (*GetAssetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAssetsResponse)
	err := c.cc.Invoke(ctx, PortfolioService_GetAssets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) GetAnnualReview(ctx context.Context, in *GetAnnualReviewRequest, opts ...grpc.CallOption) (*AnnualReview, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnnualReview)
	err := c.cc.Invoke(ctx, PortfolioService_GetAnnualReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortfolioServiceServer is the server API for PortfolioService service.
// All implementations should embed UnimplementedPortfolioServiceServer
// for forward compatibility.
type PortfolioServiceServer interface {
	CreateTrade(context.Context, *CreateTradeRequest) (*Trade, error)
	ListTrades(context.Context, *ListTradesRequest) (*ListTradesResponse, error)
	CreateDividend(context.Context, *CreateDividendRequest) (*Dividend, error)
	ListDividends(context.Context, *ListDividendsRequest) (*ListDividendsResponse, error)
	CreateCashFlow(context.Context, *CreateCashFlowRequest) (*CashFlow, error)
	ListCashFlows(context.Context, *ListCashFlowsRequest) (*ListCashFlowsResponse, error)
	ListPositions(context.Context, *Empty) (*ListPositionsResponse, error)
	CreateValuation(context.Context, *CreateValuationRequest) (*Valuation, error)
	ListValuations(context.Context, *ListValuationsRequest) (*ListValuationsResponse, error)
	GetAssets(context.Context, *GetAssetsRequest) (*GetAssetsResponse, error)
	GetAnnualReview(context.Context, *GetAnnualReviewRequest) (*AnnualReview, error)
}

// UnimplementedPortfolioServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPortfolioServiceServer struct{}

func (UnimplementedPortfolioServiceServer) CreateTrade(context.Context, *CreateTradeRequest) (*Trade, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTrade not implemented")
}
func (UnimplementedPortfolioServiceServer) ListTrades(context.Context, *ListTradesRequest) (*ListTradesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTrades not implemented")
}
func (UnimplementedPortfolioServiceServer) CreateDividend(context.Context, *CreateDividendRequest) (*Dividend, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDividend not implemented")
}
func (UnimplementedPortfolioServiceServer) ListDividends(context.Context, *ListDividendsRequest) (*ListDividendsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDividends not implemented")
}
func (UnimplementedPortfolioServiceServer) CreateCashFlow(context.Context, *CreateCashFlowRequest) (*CashFlow, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCashFlow not implemented")
}
func (UnimplementedPortfolioServiceServer) ListCashFlows(context.Context, *ListCashFlowsRequest) (*ListCashFlowsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCashFlows not implemented")
}
func (UnimplementedPortfolioServiceServer) ListPositions(context.Context, *Empty) (*ListPositionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPositions not implemented")
}
func (UnimplementedPortfolioServiceServer) CreateValuation(context.Context, *CreateValuationRequest) (*Valuation, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateValuation not implemented")
}
func (UnimplementedPortfolioServiceServer) ListValuations(context.Context, *ListValuationsRequest) (*ListValuationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListValuations not implemented")
}
func (UnimplementedPortfolioServiceServer) GetAssets(context.Context, *GetAssetsRequest) (*GetAssetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAssets not implemented")
}
func (UnimplementedPortfolioServiceServer) GetAnnualReview(context.Context, *GetAnnualReviewRequest) (*AnnualReview, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAnnualReview not implemented")
}
func (UnimplementedPortfolioServiceServer) testEmbeddedByValue() {}

// UnsafePortfolioServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PortfolioServiceServer will
// result in compilation errors.
type UnsafePortfolioServiceServer interface {
	mustEmbedUnimplementedPortfolioServiceServer()
}

func RegisterPortfolioServiceServer(s grpc.ServiceRegistrar, srv PortfolioServiceServer) {
	// If the following call panics, it indicates UnimplementedPortfolioServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PortfolioService_ServiceDesc, srv)
}

func _PortfolioService_CreateTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTradeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).CreateTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_CreateTrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).CreateTrade(ctx, req.(*CreateTradeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_ListTrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).ListTrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_ListTrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).ListTrades(ctx, req.(*ListTradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_CreateDividend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDividendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).CreateDividend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_CreateDividend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).CreateDividend(ctx, req.(*CreateDividendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_ListDividends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDividendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).ListDividends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_ListDividends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).ListDividends(ctx, req.(*ListDividendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_CreateCashFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCashFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).CreateCashFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_CreateCashFlow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).CreateCashFlow(ctx, req.(*CreateCashFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_ListCashFlows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCashFlowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).ListCashFlows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_ListCashFlows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).ListCashFlows(ctx, req.(*ListCashFlowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_ListPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).ListPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_ListPositions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).ListPositions(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_CreateValuation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateValuationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).CreateValuation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_CreateValuation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).CreateValuation(ctx, req.(*CreateValuationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_ListValuations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListValuationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).ListValuations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_ListValuations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).ListValuations(ctx, req.(*ListValuationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_GetAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).GetAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_GetAssets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).GetAssets(ctx, req.(*GetAssetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_GetAnnualReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnnualReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).GetAnnualReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_GetAnnualReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).GetAnnualReview(ctx, req.(*GetAnnualReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PortfolioService_ServiceDesc is the grpc.ServiceDesc for PortfolioService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PortfolioService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "guanlan.v1.PortfolioService",
	HandlerType: (*PortfolioServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTrade",
			Handler:    _PortfolioService_CreateTrade_Handler,
		},
		{
			MethodName: "ListTrades",
			Handler:    _PortfolioService_ListTrades_Handler,
		},
		{
			MethodName: "CreateDividend",
			Handler:    _PortfolioService_CreateDividend_Handler,
		},
		{
			MethodName: "ListDividends",
			Handler:    _PortfolioService_ListDividends_Handler,
		},
		{
			MethodName: "CreateCashFlow",
			Handler:    _PortfolioService_CreateCashFlow_Handler,
		},
		{
			MethodName: "ListCashFlows",
			Handler:    _PortfolioService_ListCashFlows_Handler,
		},
		{
			MethodName: "ListPositions",
			Handler:    _PortfolioService_ListPositions_Handler,
		},
		{
			MethodName: "CreateValuation",
			Handler:    _PortfolioService_CreateValuation_Handler,
		},
		{
			MethodName: "ListValuations",
			Handler:    _PortfolioService_ListValuations_Handler,
		},
		{
			MethodName: "GetAssets",
			Handler:    _PortfolioService_GetAssets_Handler,
		},
		{
			MethodName: "GetAnnualReview",
			Handler:    _PortfolioService_GetAnnualReview_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/api.proto",
}

const (
	DataService_ListIndexes_FullMethodName           = "/guanlan.v1.DataService/ListIndexes"
	DataService_ListIndexConstituents_FullMethodName = "/guanlan.v1.DataService/ListIndexConstituents"
	DataService_InitTrainingIndex_FullMethodName     = "/guanlan.v1.DataService/InitTrainingIndex"
	DataService_ListStocks_FullMethodName            = "/guanlan.v1.DataService/ListStocks"
	DataService_ListDailyBars_FullMethodName         = "/guanlan.v1.DataService/ListDailyBars"
	DataService_SyncStock_FullMethodName             = "/guanlan.v1.DataService/SyncStock"
	DataService_ListDataTasks_FullMethodName         = "/guanlan.v1.DataService/ListDataTasks"
	DataService_ListStockPool_FullMethodName         = "/guanlan.v1.DataService/ListStockPool"
	DataService_UpsertStockPoolItem_FullMethodName   = "/guanlan.v1.DataService/UpsertStockPoolItem"
)

// DataServiceClient is the client API for DataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataServiceClient interface {
	ListIndexes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListIndexesResponse, error)
	ListIndexConstituents(ctx context.Context, in *ListIndexConstituentsRequest, opts ...grpc.CallOption) (*ListIndexConstituentsResponse, error)
	InitTrainingIndex(ctx context.Context, in *InitTrainingIndexRequest, opts ...grpc.CallOption) (*Task, error)
	ListStocks(ctx context.Context, in *ListStocksRequest, opts ...grpc.CallOption) (*ListStocksResponse, error)
	ListDailyBars(ctx context.Context, in *ListDailyBarsRequest, opts ...grpc.CallOption) (*ListDailyBarsResponse, error)
	SyncStock(ctx context.Context, in *SyncStockRequest, opts ...grpc.CallOption) (*Task, error)
	ListDataTasks(ctx context.Context, in *ListDataTasksRequest, opts ...grpc.CallOption) (*ListDataTasksResponse, error)
	ListStockPool(ctx context.Context, in *ListStockPoolRequest, opts ...grpc.CallOption) (*ListStockPoolResponse, error)
	UpsertStockPoolItem(ctx context.Context, in *UpsertStockPoolItemRequest, opts ...grpc.CallOption) (*StockPoolItem, error)
}

type dataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataServiceClient(cc grpc.ClientConnInterface) DataServiceClient {
	return &dataServiceClient{cc}
}

func (c *dataServiceClient) ListIndexes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListIndexesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIndexesResponse)
	err := c.cc.Invoke(ctx, DataService_ListIndexes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) ListIndexConstituents(ctx context.Context, in *ListIndexConstituentsRequest, opts ...grpc.CallOption) (*ListIndexConstituentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIndexConstituentsResponse)
	err := c.cc.Invoke(ctx, DataService_ListIndexConstituents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) InitTrainingIndex(ctx context.Context, in *InitTrainingIndexRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, DataService_InitTrainingIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) ListStocks(ctx context.Context, in *ListStocksRequest, opts ...grpc.CallOption) (*ListStocksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStocksResponse)
	err := c.cc.Invoke(ctx, DataService_ListStocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) ListDailyBars(ctx context.Context, in *ListDailyBarsRequest, opts ...grpc.CallOption) (*ListDailyBarsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDailyBarsResponse)
	err := c.cc.Invoke(ctx, DataService_ListDailyBars_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) SyncStock(ctx context.Context, in *SyncStockRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, DataService_SyncStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) ListDataTasks(ctx context.Context, in *ListDataTasksRequest, opts ...grpc.CallOption) (*ListDataTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDataTasksResponse)
	err := c.cc.Invoke(ctx, DataService_ListDataTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) ListStockPool(ctx context.Context, in *ListStockPoolRequest, opts ...grpc.CallOption) (*ListStockPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStockPoolResponse)
	err := c.cc.Invoke(ctx, DataService_ListStockPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataServiceClient) UpsertStockPoolItem(ctx context.Context, in *UpsertStockPoolItemRequest, opts ...grpc.CallOption) (*StockPoolItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockPoolItem)
	err := c.cc.Invoke(ctx, DataService_UpsertStockPoolItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServiceServer is the server API for DataService service.
// All implementations should embed UnimplementedDataServiceServer
// for forward compatibility.
type DataServiceServer interface {
	ListIndexes(context.Context, *Empty) (*ListIndexesResponse, error)
	ListIndexConstituents(context.Context, *ListIndexConstituentsRequest) (*ListIndexConstituentsResponse, error)
	InitTrainingIndex(context.Context, *InitTrainingIndexRequest) (*Task, error)
	ListStocks(context.Context, *ListStocksRequest) (*ListStocksResponse, error)
	ListDailyBars(context.Context, *ListDailyBarsRequest) (*ListDailyBarsResponse, error)
	SyncStock(context.Context, *SyncStockRequest) (*Task, error)
	ListDataTasks(context.Context, *ListDataTasksRequest) (*ListDataTasksResponse, error)
	ListStockPool(context.Context, *ListStockPoolRequest) (*ListStockPoolResponse, error)
	UpsertStockPoolItem(context.Context, *UpsertStockPoolItemRequest) (*StockPoolItem, error)
}

// UnimplementedDataServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataServiceServer struct{}

func (UnimplementedDataServiceServer) ListIndexes(context.Context, *Empty) (*ListIndexesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIndexes not implemented")
}
func (UnimplementedDataServiceServer) ListIndexConstituents(context.Context, *ListIndexConstituentsRequest) (*ListIndexConstituentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIndexConstituents not implemented")
}
func (UnimplementedDataServiceServer) InitTrainingIndex(context.Context, *InitTrainingIndexRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method InitTrainingIndex not implemented")
}
func (UnimplementedDataServiceServer) ListStocks(context.Context, *ListStocksRequest) (*ListStocksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStocks not implemented")
}
func (UnimplementedDataServiceServer) ListDailyBars(context.Context, *ListDailyBarsRequest) (*ListDailyBarsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDailyBars not implemented")
}
func (UnimplementedDataServiceServer) SyncStock(context.Context, *SyncStockRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncStock not implemented")
}
func (UnimplementedDataServiceServer) ListDataTasks(context.Context, *ListDataTasksRequest) (*ListDataTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDataTasks not implemented")
}
func (UnimplementedDataServiceServer) ListStockPool(context.Context, *ListStockPoolRequest) (*ListStockPoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStockPool not implemented")
}
func (UnimplementedDataServiceServer) UpsertStockPoolItem(context.Context, *UpsertStockPoolItemRequest) (*StockPoolItem, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertStockPoolItem not implemented")
}
func (UnimplementedDataServiceServer) testEmbeddedByValue() {}

// UnsafeDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataServiceServer will
// result in compilation errors.
type UnsafeDataServiceServer interface {
	mustEmbedUnimplementedDataServiceServer()
}

func RegisterDataServiceServer(s grpc.ServiceRegistrar, srv DataServiceServer) {
	// If the following call panics, it indicates UnimplementedDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataService_ServiceDesc, srv)
}

func _DataService_ListIndexes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).ListIndexes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_ListIndexes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).ListIndexes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_ListIndexConstituents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIndexConstituentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).ListIndexConstituents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_ListIndexConstituents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).ListIndexConstituents(ctx, req.(*ListIndexConstituentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_InitTrainingIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitTrainingIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).InitTrainingIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_InitTrainingIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).InitTrainingIndex(ctx, req.(*InitTrainingIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_ListStocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).ListStocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_ListStocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).ListStocks(ctx, req.(*ListStocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_ListDailyBars_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDailyBarsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).ListDailyBars(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_ListDailyBars_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).ListDailyBars(ctx, req.(*ListDailyBarsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_SyncStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).SyncStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_SyncStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).SyncStock(ctx, req.(*SyncStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_ListDataTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDataTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).ListDataTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_ListDataTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).ListDataTasks(ctx, req.(*ListDataTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_ListStockPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStockPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).ListStockPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_ListStockPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).ListStockPool(ctx, req.(*ListStockPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataService_UpsertStockPoolItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertStockPoolItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServiceServer).UpsertStockPoolItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataService_UpsertStockPoolItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServiceServer).UpsertStockPoolItem(ctx, req.(*UpsertStockPoolItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataService_ServiceDesc is the grpc.ServiceDesc for DataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "guanlan.v1.DataService",
	HandlerType: (*DataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListIndexes",
			Handler:    _DataService_ListIndexes_Handler,
		},
		{
			MethodName: "ListIndexConstituents",
			Handler:    _DataService_ListIndexConstituents_Handler,
		},
		{
			MethodName: "InitTrainingIndex",
			Handler:    _DataService_InitTrainingIndex_Handler,
		},
		{
			MethodName: "ListStocks",
			Handler:    _DataService_ListStocks_Handler,
		},
		{
			MethodName: "ListDailyBars",
			Handler:    _DataService_ListDailyBars_Handler,
		},
		{
			MethodName: "SyncStock",
			Handler:    _DataService_SyncStock_Handler,
		},
		{
			MethodName: "ListDataTasks",
			Handler:    _DataService_ListDataTasks_Handler,
		},
		{
			MethodName: "ListStockPool",
			Handler:    _DataService_ListStockPool_Handler,
		},
		{
			MethodName: "UpsertStockPoolItem",
			Handler:    _DataService_UpsertStockPoolItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/api.proto",
}
