// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: quant/v1/api.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationTaskServiceGetTask = "/quant.v1.TaskService/GetTask"
const OperationTaskServiceListTasks = "/quant.v1.TaskService/ListTasks"
const OperationTaskServiceRetryTask = "/quant.v1.TaskService/RetryTask"

type TaskServiceHTTPServer interface {
	GetTask(context.Context, *GetTaskRequest) (*Task, error)
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	RetryTask(context.Context, *RetryTaskRequest) (*RetryTaskResponse, error)
}

func RegisterTaskServiceHTTPServer(s *http.Server, srv TaskServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/tasks", _TaskService_ListTasks0_HTTP_Handler(srv))
	r.GET("/api/tasks/{task_id}", _TaskService_GetTask0_HTTP_Handler(srv))
	r.POST("/api/tasks/{task_id}/retry", _TaskService_RetryTask0_HTTP_Handler(srv))
}

func _TaskService_ListTasks0_HTTP_Handler(srv TaskServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTasksRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTaskServiceListTasks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTasks(ctx, req.(*ListTasksRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTasksResponse)
		return ctx.Result(200, reply)
	}
}

func _TaskService_GetTask0_HTTP_Handler(srv TaskServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTaskRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTaskServiceGetTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTask(ctx, req.(*GetTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Task)
		return ctx.Result(200, reply)
	}
}

func _TaskService_RetryTask0_HTTP_Handler(srv TaskServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RetryTaskRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTaskServiceRetryTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RetryTask(ctx, req.(*RetryTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RetryTaskResponse)
		return ctx.Result(200, reply)
	}
}

type TaskServiceHTTPClient interface {
	GetTask(ctx context.Context, req *GetTaskRequest, opts ...http.CallOption) (rsp *Task, err error)
	ListTasks(ctx context.Context, req *ListTasksRequest, opts ...http.CallOption) (rsp *ListTasksResponse, err error)
	RetryTask(ctx context.Context, req *RetryTaskRequest, opts ...http.CallOption) (rsp *RetryTaskResponse, err error)
}

type TaskServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewTaskServiceHTTPClient(client *http.Client) TaskServiceHTTPClient {
	return &TaskServiceHTTPClientImpl{client}
}

func (c *TaskServiceHTTPClientImpl) GetTask(ctx context.Context, in *GetTaskRequest, opts ...http.CallOption) (*Task, error) {
	var out Task
	pattern := "/api/tasks/{task_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTaskServiceGetTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TaskServiceHTTPClientImpl) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...http.CallOption) (*ListTasksResponse, error) {
	var out ListTasksResponse
	pattern := "/api/tasks"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTaskServiceListTasks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *TaskServiceHTTPClientImpl) RetryTask(ctx context.Context, in *RetryTaskRequest, opts ...http.CallOption) (*RetryTaskResponse, error) {
	var out RetryTaskResponse
	pattern := "/api/tasks/{task_id}/retry"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTaskServiceRetryTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationWatchlistServiceAddWatchlistItem = "/quant.v1.WatchlistService/AddWatchlistItem"
const OperationWatchlistServiceListWatchlist = "/quant.v1.WatchlistService/ListWatchlist"
const OperationWatchlistServiceRemoveWatchlistItem = "/quant.v1.WatchlistService/RemoveWatchlistItem"

type WatchlistServiceHTTPServer interface {
	AddWatchlistItem(context.Context, *AddWatchlistItemRequest) (*WatchlistItem, error)
	ListWatchlist(context.Context, *ListWatchlistRequest) (*ListWatchlistResponse, error)
	RemoveWatchlistItem(context.Context, *RemoveWatchlistItemRequest) (*WatchlistItem, error)
}

func RegisterWatchlistServiceHTTPServer(s *http.Server, srv WatchlistServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/watchlist", _WatchlistService_ListWatchlist0_HTTP_Handler(srv))
	r.POST("/api/watchlist/items", _WatchlistService_AddWatchlistItem0_HTTP_Handler(srv))
	r.DELETE("/api/watchlist/items/{stock_code}", _WatchlistService_RemoveWatchlistItem0_HTTP_Handler(srv))
}

func _WatchlistService_ListWatchlist0_HTTP_Handler(srv WatchlistServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListWatchlistRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWatchlistServiceListWatchlist)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListWatchlist(ctx, req.(*ListWatchlistRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListWatchlistResponse)
		return ctx.Result(200, reply)
	}
}

func _WatchlistService_AddWatchlistItem0_HTTP_Handler(srv WatchlistServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddWatchlistItemRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWatchlistServiceAddWatchlistItem)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddWatchlistItem(ctx, req.(*AddWatchlistItemRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*WatchlistItem)
		return ctx.Result(200, reply)
	}
}

func _WatchlistService_RemoveWatchlistItem0_HTTP_Handler(srv WatchlistServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RemoveWatchlistItemRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWatchlistServiceRemoveWatchlistItem)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RemoveWatchlistItem(ctx, req.(*RemoveWatchlistItemRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*WatchlistItem)
		return ctx.Result(200, reply)
	}
}

type WatchlistServiceHTTPClient interface {
	AddWatchlistItem(ctx context.Context, req *AddWatchlistItemRequest, opts ...http.CallOption) (rsp *WatchlistItem, err error)
	ListWatchlist(ctx context.Context, req *ListWatchlistRequest, opts ...http.CallOption) (rsp *ListWatchlistResponse, err error)
	RemoveWatchlistItem(ctx context.Context, req *RemoveWatchlistItemRequest, opts ...http.CallOption) (rsp *WatchlistItem, err error)
}

type WatchlistServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewWatchlistServiceHTTPClient(client *http.Client) WatchlistServiceHTTPClient {
	return &WatchlistServiceHTTPClientImpl{client}
}

func (c *WatchlistServiceHTTPClientImpl) AddWatchlistItem(ctx context.Context, in *AddWatchlistItemRequest, opts ...http.CallOption) (*WatchlistItem, error) {
	var out WatchlistItem
	pattern := "/api/watchlist/items"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWatchlistServiceAddWatchlistItem))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WatchlistServiceHTTPClientImpl) ListWatchlist(ctx context.Context, in *ListWatchlistRequest, opts ...http.CallOption) (*ListWatchlistResponse, error) {
	var out ListWatchlistResponse
	pattern := "/api/watchlist"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWatchlistServiceListWatchlist))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WatchlistServiceHTTPClientImpl) RemoveWatchlistItem(ctx context.Context, in *RemoveWatchlistItemRequest, opts ...http.CallOption) (*WatchlistItem, error) {
	var out WatchlistItem
	pattern := "/api/watchlist/items/{stock_code}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWatchlistServiceRemoveWatchlistItem))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationPortfolioServiceCreateCashFlow = "/quant.v1.PortfolioService/CreateCashFlow"
const OperationPortfolioServiceCreateDividend = "/quant.v1.PortfolioService/CreateDividend"
const OperationPortfolioServiceCreateTrade = "/quant.v1.PortfolioService/CreateTrade"
const OperationPortfolioServiceCreateValuation = "/quant.v1.PortfolioService/CreateValuation"
const OperationPortfolioServiceGetAnnualReview = "/quant.v1.PortfolioService/GetAnnualReview"
const OperationPortfolioServiceGetAssets = "/quant.v1.PortfolioService/GetAssets"
const OperationPortfolioServiceListCashFlows = "/quant.v1.PortfolioService/ListCashFlows"
const OperationPortfolioServiceListDividends = "/quant.v1.PortfolioService/ListDividends"
const OperationPortfolioServiceListPositions = "/quant.v1.PortfolioService/ListPositions"
const OperationPortfolioServiceListTrades = "/quant.v1.PortfolioService/ListTrades"
const OperationPortfolioServiceListValuations = "/quant.v1.PortfolioService/ListValuations"

type PortfolioServiceHTTPServer interface {
	CreateCashFlow(context.Context, *CreateCashFlowRequest) (*CashFlow, error)
	CreateDividend(context.Context, *CreateDividendRequest) (*Dividend, error)
	CreateTrade(context.Context, *CreateTradeRequest) (*Trade, error)
	CreateValuation(context.Context, *CreateValuationRequest) (*Valuation, error)
	GetAnnualReview(context.Context, *GetAnnualReviewRequest) (*AnnualReview, error)
	GetAssets(context.Context, *GetAssetsRequest) (*GetAssetsResponse, error)
	ListCashFlows(context.Context, *ListCashFlowsRequest) (*ListCashFlowsResponse, error)
	ListDividends(context.Context, *ListDividendsRequest) (*ListDividendsResponse, error)
	ListPositions(context.Context, *Empty) (*ListPositionsResponse, error)
	ListTrades(context.Context, *ListTradesRequest) (*ListTradesResponse, error)
	ListValuations(context.Context, *ListValuationsRequest) (*ListValuationsResponse, error)
}

func RegisterPortfolioServiceHTTPServer(s *http.Server, srv PortfolioServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/portfolio/trades", _PortfolioService_CreateTrade0_HTTP_Handler(srv))
	r.GET("/api/portfolio/trades", _PortfolioService_ListTrades0_HTTP_Handler(srv))
	r.POST("/api/portfolio/dividends", _PortfolioService_CreateDividend0_HTTP_Handler(srv))
	r.GET("/api/portfolio/dividends", _PortfolioService_ListDividends0_HTTP_Handler(srv))
	r.POST("/api/portfolio/cash-flows", _PortfolioService_CreateCashFlow0_HTTP_Handler(srv))
	r.GET("/api/portfolio/cash-flows", _PortfolioService_ListCashFlows0_HTTP_Handler(srv))
	r.GET("/api/portfolio/positions", _PortfolioService_ListPositions0_HTTP_Handler(srv))
	r.POST("/api/portfolio/valuations", _PortfolioService_CreateValuation0_HTTP_Handler(srv))
	r.GET("/api/portfolio/valuations", _PortfolioService_ListValuations0_HTTP_Handler(srv))
	r.GET("/api/portfolio/assets", _PortfolioService_GetAssets0_HTTP_Handler(srv))
	r.GET("/api/portfolio/annual-reviews", _PortfolioService_GetAnnualReview0_HTTP_Handler(srv))
}

func _PortfolioService_CreateTrade0_HTTP_Handler(srv PortfolioServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTradeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPortfolioServiceCreateTrade)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateTrade(ctx, req.(*CreateTradeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Trade)
		return ctx.Result(200, reply)
	}
}

func _PortfolioService_ListTrades0_HTTP_Handler(srv PortfolioServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTradesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPortfolioServiceListTrades)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTrades(ctx, req.(*ListTradesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTradesResponse)
		return ctx.Result(200, reply)
	}
}

func _PortfolioService_CreateDividend0_HTTP_Handler(srv PortfolioServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateDividendRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPortfolioServiceCreateDividend)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateDividend(ctx, req.(*CreateDividendRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Dividend)
		return ctx.Result(200, reply)
	}
}

func _PortfolioService_ListDividends0_HTTP_Handler(srv PortfolioServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListDividendsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPortfolioServiceListDividends)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListDividends(ctx, req.(*ListDividendsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListDividendsResponse)
		return ctx.Result(200, reply)
	}
}

func _PortfolioService_CreateCashFlow0_HTTP_Handler(srv PortfolioServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateCashFlowRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPortfolioServiceCreateCashFlow)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateCashFlow(ctx, req.(*CreateCashFlowRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CashFlow)
		return ctx.Result(200, reply)
	}
}

func _PortfolioService_ListCashFlows0_HTTP_Handler(srv PortfolioServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCashFlowsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPortfolioServiceListCashFlows)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCashFlows(ctx, req.(*ListCashFlowsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCashFlowsResponse)
		return ctx.Result(200, reply)
	}
}

func _PortfolioService_ListPositions0_HTTP_Handler(srv PortfolioServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPortfolioServiceListPositions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPositions(ctx, req.(*Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPositionsResponse)
		return ctx.Result(200, reply)
	}
}

func _PortfolioService_CreateValuation0_HTTP_Handler(srv PortfolioServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateValuationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPortfolioServiceCreateValuation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateValuation(ctx, req.(*CreateValuationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Valuation)
		return ctx.Result(200, reply)
	}
}

func _PortfolioService_ListValuations0_HTTP_Handler(srv PortfolioServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListValuationsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPortfolioServiceListValuations)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListValuations(ctx, req.(*ListValuationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListValuationsResponse)
		return ctx.Result(200, reply)
	}
}

func _PortfolioService_GetAssets0_HTTP_Handler(srv PortfolioServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAssetsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPortfolioServiceGetAssets)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAssets(ctx, req.(*GetAssetsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAssetsResponse)
		return ctx.Result(200, reply)
	}
}

func _PortfolioService_GetAnnualReview0_HTTP_Handler(srv PortfolioServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAnnualReviewRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPortfolioServiceGetAnnualReview)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAnnualReview(ctx, req.(*GetAnnualReviewRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AnnualReview)
		return ctx.Result(200, reply)
	}
}

type PortfolioServiceHTTPClient interface {
	CreateCashFlow(ctx context.Context, req *CreateCashFlowRequest, opts ...http.CallOption) (rsp *CashFlow, err error)
	CreateDividend(ctx context.Context, req *CreateDividendRequest, opts ...http.CallOption) (rsp *Dividend, err error)
	CreateTrade(ctx context.Context, req *CreateTradeRequest, opts ...http.CallOption) (rsp *Trade, err error)
	CreateValuation(ctx context.Context, req *CreateValuationRequest, opts ...http.CallOption) (rsp *Valuation, err error)
	GetAnnualReview(ctx context.Context, req *GetAnnualReviewRequest, opts ...http.CallOption) (rsp *AnnualReview, err error)
	GetAssets(ctx context.Context, req *GetAssetsRequest, opts ...http.CallOption) (rsp *GetAssetsResponse, err error)
	ListCashFlows(ctx context.Context, req *ListCashFlowsRequest, opts ...http.CallOption) (rsp *ListCashFlowsResponse, err error)
	ListDividends(ctx context.Context, req *ListDividendsRequest, opts ...http.CallOption) (rsp *ListDividendsResponse, err error)
	ListPositions(ctx context.Context, req *Empty, opts ...http.CallOption) (rsp *ListPositionsResponse, err error)
	ListTrades(ctx context.Context, req *ListTradesRequest, opts ...http.CallOption) (rsp *ListTradesResponse, err error)
	ListValuations(ctx context.Context, req *ListValuationsRequest, opts ...http.CallOption) (rsp *ListValuationsResponse, err error)
}

type PortfolioServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewPortfolioServiceHTTPClient(client *http.Client) PortfolioServiceHTTPClient {
	return &PortfolioServiceHTTPClientImpl{client}
}

func (c *PortfolioServiceHTTPClientImpl) CreateCashFlow(ctx context.Context, in *CreateCashFlowRequest, opts ...http.CallOption) (*CashFlow, error) {
	var out CashFlow
	pattern := "/api/portfolio/cash-flows"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPortfolioServiceCreateCashFlow))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PortfolioServiceHTTPClientImpl) CreateDividend(ctx context.Context, in *CreateDividendRequest, opts ...http.CallOption) (*Dividend, error) {
	var out Dividend
	pattern := "/api/portfolio/dividends"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPortfolioServiceCreateDividend))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PortfolioServiceHTTPClientImpl) CreateTrade(ctx context.Context, in *CreateTradeRequest, opts ...http.CallOption) (*Trade, error) {
	var out Trade
	pattern := "/api/portfolio/trades"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPortfolioServiceCreateTrade))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PortfolioServiceHTTPClientImpl) CreateValuation(ctx context.Context, in *CreateValuationRequest, opts ...http.CallOption) (*Valuation, error) {
	var out Valuation
	pattern := "/api/portfolio/valuations"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPortfolioServiceCreateValuation))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PortfolioServiceHTTPClientImpl) GetAnnualReview(ctx context.Context, in *GetAnnualReviewRequest, opts ...http.CallOption) (*AnnualReview, error) {
	var out AnnualReview
	pattern := "/api/portfolio/annual-reviews"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPortfolioServiceGetAnnualReview))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PortfolioServiceHTTPClientImpl) GetAssets(ctx context.Context, in *GetAssetsRequest, opts ...http.CallOption) (*GetAssetsResponse, error) {
	var out GetAssetsResponse
	pattern := "/api/portfolio/assets"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPortfolioServiceGetAssets))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PortfolioServiceHTTPClientImpl) ListCashFlows(ctx context.Context, in *ListCashFlowsRequest, opts ...http.CallOption) (*ListCashFlowsResponse, error) {
	var out ListCashFlowsResponse
	pattern := "/api/portfolio/cash-flows"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPortfolioServiceListCashFlows))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PortfolioServiceHTTPClientImpl) ListDividends(ctx context.Context, in *ListDividendsRequest, opts ...http.CallOption) (*ListDividendsResponse, error) {
	var out ListDividendsResponse
	pattern := "/api/portfolio/dividends"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPortfolioServiceListDividends))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PortfolioServiceHTTPClientImpl) ListPositions(ctx context.Context, in *Empty, opts ...http.CallOption) (*ListPositionsResponse, error) {
	var out ListPositionsResponse
	pattern := "/api/portfolio/positions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPortfolioServiceListPositions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PortfolioServiceHTTPClientImpl) ListTrades(ctx context.Context, in *ListTradesRequest, opts ...http.CallOption) (*ListTradesResponse, error) {
	var out ListTradesResponse
	pattern := "/api/portfolio/trades"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPortfolioServiceListTrades))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *PortfolioServiceHTTPClientImpl) ListValuations(ctx context.Context, in *ListValuationsRequest, opts ...http.CallOption) (*ListValuationsResponse, error) {
	var out ListValuationsResponse
	pattern := "/api/portfolio/valuations"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPortfolioServiceListValuations))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationDataServiceListDailyBars = "/quant.v1.DataService/ListDailyBars"
const OperationDataServiceListDataTasks = "/quant.v1.DataService/ListDataTasks"
const OperationDataServiceListStockPool = "/quant.v1.DataService/ListStockPool"
const OperationDataServiceListStocks = "/quant.v1.DataService/ListStocks"
const OperationDataServiceSyncStock = "/quant.v1.DataService/SyncStock"
const OperationDataServiceUpsertStockPoolItem = "/quant.v1.DataService/UpsertStockPoolItem"

type DataServiceHTTPServer interface {
	ListDailyBars(context.Context, *ListDailyBarsRequest) (*ListDailyBarsResponse, error)
	ListDataTasks(context.Context, *ListDataTasksRequest) (*ListDataTasksResponse, error)
	ListStockPool(context.Context, *ListStockPoolRequest) (*ListStockPoolResponse, error)
	ListStocks(context.Context, *ListStocksRequest) (*ListStocksResponse, error)
	SyncStock(context.Context, *SyncStockRequest) (*Task, error)
	UpsertStockPoolItem(context.Context, *UpsertStockPoolItemRequest) (*StockPoolItem, error)
}

func RegisterDataServiceHTTPServer(s *http.Server, srv DataServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/data/stocks", _DataService_ListStocks0_HTTP_Handler(srv))
	r.GET("/api/data/stocks/{stock_code}/daily-bars", _DataService_ListDailyBars0_HTTP_Handler(srv))
	r.POST("/api/data/stocks/{stock_code}/sync", _DataService_SyncStock0_HTTP_Handler(srv))
	r.GET("/api/data/tasks", _DataService_ListDataTasks0_HTTP_Handler(srv))
	r.GET("/api/data/pool", _DataService_ListStockPool0_HTTP_Handler(srv))
	r.POST("/api/data/pool/items", _DataService_UpsertStockPoolItem0_HTTP_Handler(srv))
}

func _DataService_ListStocks0_HTTP_Handler(srv DataServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListStocksRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDataServiceListStocks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListStocks(ctx, req.(*ListStocksRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListStocksResponse)
		return ctx.Result(200, reply)
	}
}

func _DataService_ListDailyBars0_HTTP_Handler(srv DataServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListDailyBarsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDataServiceListDailyBars)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListDailyBars(ctx, req.(*ListDailyBarsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListDailyBarsResponse)
		return ctx.Result(200, reply)
	}
}

func _DataService_SyncStock0_HTTP_Handler(srv DataServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SyncStockRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDataServiceSyncStock)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SyncStock(ctx, req.(*SyncStockRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Task)
		return ctx.Result(200, reply)
	}
}

func _DataService_ListDataTasks0_HTTP_Handler(srv DataServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListDataTasksRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDataServiceListDataTasks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListDataTasks(ctx, req.(*ListDataTasksRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListDataTasksResponse)
		return ctx.Result(200, reply)
	}
}

func _DataService_ListStockPool0_HTTP_Handler(srv DataServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListStockPoolRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDataServiceListStockPool)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListStockPool(ctx, req.(*ListStockPoolRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListStockPoolResponse)
		return ctx.Result(200, reply)
	}
}

func _DataService_UpsertStockPoolItem0_HTTP_Handler(srv DataServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpsertStockPoolItemRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDataServiceUpsertStockPoolItem)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpsertStockPoolItem(ctx, req.(*UpsertStockPoolItemRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StockPoolItem)
		return ctx.Result(200, reply)
	}
}

type DataServiceHTTPClient interface {
	ListDailyBars(ctx context.Context, req *ListDailyBarsRequest, opts ...http.CallOption) (rsp *ListDailyBarsResponse, err error)
	ListDataTasks(ctx context.Context, req *ListDataTasksRequest, opts ...http.CallOption) (rsp *ListDataTasksResponse, err error)
	ListStockPool(ctx context.Context, req *ListStockPoolRequest, opts ...http.CallOption) (rsp *ListStockPoolResponse, err error)
	ListStocks(ctx context.Context, req *ListStocksRequest, opts ...http.CallOption) (rsp *ListStocksResponse, err error)
	SyncStock(ctx context.Context, req *SyncStockRequest, opts ...http.CallOption) (rsp *Task, err error)
	UpsertStockPoolItem(ctx context.Context, req *UpsertStockPoolItemRequest, opts ...http.CallOption) (rsp *StockPoolItem, err error)
}

type DataServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewDataServiceHTTPClient(client *http.Client) DataServiceHTTPClient {
	return &DataServiceHTTPClientImpl{client}
}

func (c *DataServiceHTTPClientImpl) ListDailyBars(ctx context.Context, in *ListDailyBarsRequest, opts ...http.CallOption) (*ListDailyBarsResponse, error) {
	var out ListDailyBarsResponse
	pattern := "/api/data/stocks/{stock_code}/daily-bars"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDataServiceListDailyBars))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DataServiceHTTPClientImpl) ListDataTasks(ctx context.Context, in *ListDataTasksRequest, opts ...http.CallOption) (*ListDataTasksResponse, error) {
	var out ListDataTasksResponse
	pattern := "/api/data/tasks"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDataServiceListDataTasks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DataServiceHTTPClientImpl) ListStockPool(ctx context.Context, in *ListStockPoolRequest, opts ...http.CallOption) (*ListStockPoolResponse, error) {
	var out ListStockPoolResponse
	pattern := "/api/data/pool"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDataServiceListStockPool))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DataServiceHTTPClientImpl) ListStocks(ctx context.Context, in *ListStocksRequest, opts ...http.CallOption) (*ListStocksResponse, error) {
	var out ListStocksResponse
	pattern := "/api/data/stocks"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDataServiceListStocks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DataServiceHTTPClientImpl) SyncStock(ctx context.Context, in *SyncStockRequest, opts ...http.CallOption) (*Task, error) {
	var out Task
	pattern := "/api/data/stocks/{stock_code}/sync"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDataServiceSyncStock))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *DataServiceHTTPClientImpl) UpsertStockPoolItem(ctx context.Context, in *UpsertStockPoolItemRequest, opts ...http.CallOption) (*StockPoolItem, error) {
	var out StockPoolItem
	pattern := "/api/data/pool/items"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDataServiceUpsertStockPoolItem))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationAnalysisServiceListPredictions = "/quant.v1.AnalysisService/ListPredictions"
const OperationAnalysisServicePredictOnDemand = "/quant.v1.AnalysisService/PredictOnDemand"
const OperationAnalysisServiceRunAnalysis = "/quant.v1.AnalysisService/RunAnalysis"

type AnalysisServiceHTTPServer interface {
	ListPredictions(context.Context, *ListPredictionsRequest) (*ListPredictionsResponse, error)
	PredictOnDemand(context.Context, *PredictOnDemandRequest) (*Prediction, error)
	RunAnalysis(context.Context, *RunAnalysisRequest) (*Task, error)
}

func RegisterAnalysisServiceHTTPServer(s *http.Server, srv AnalysisServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/analysis/run", _AnalysisService_RunAnalysis0_HTTP_Handler(srv))
	r.POST("/api/analysis/predict", _AnalysisService_PredictOnDemand0_HTTP_Handler(srv))
	r.GET("/api/analysis/results", _AnalysisService_ListPredictions0_HTTP_Handler(srv))
}

func _AnalysisService_RunAnalysis0_HTTP_Handler(srv AnalysisServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RunAnalysisRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAnalysisServiceRunAnalysis)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RunAnalysis(ctx, req.(*RunAnalysisRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Task)
		return ctx.Result(200, reply)
	}
}

func _AnalysisService_PredictOnDemand0_HTTP_Handler(srv AnalysisServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PredictOnDemandRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAnalysisServicePredictOnDemand)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PredictOnDemand(ctx, req.(*PredictOnDemandRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Prediction)
		return ctx.Result(200, reply)
	}
}

func _AnalysisService_ListPredictions0_HTTP_Handler(srv AnalysisServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListPredictionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAnalysisServiceListPredictions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPredictions(ctx, req.(*ListPredictionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPredictionsResponse)
		return ctx.Result(200, reply)
	}
}

type AnalysisServiceHTTPClient interface {
	ListPredictions(ctx context.Context, req *ListPredictionsRequest, opts ...http.CallOption) (rsp *ListPredictionsResponse, err error)
	PredictOnDemand(ctx context.Context, req *PredictOnDemandRequest, opts ...http.CallOption) (rsp *Prediction, err error)
	RunAnalysis(ctx context.Context, req *RunAnalysisRequest, opts ...http.CallOption) (rsp *Task, err error)
}

type AnalysisServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAnalysisServiceHTTPClient(client *http.Client) AnalysisServiceHTTPClient {
	return &AnalysisServiceHTTPClientImpl{client}
}

func (c *AnalysisServiceHTTPClientImpl) ListPredictions(ctx context.Context, in *ListPredictionsRequest, opts ...http.CallOption) (*ListPredictionsResponse, error) {
	var out ListPredictionsResponse
	pattern := "/api/analysis/results"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAnalysisServiceListPredictions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AnalysisServiceHTTPClientImpl) PredictOnDemand(ctx context.Context, in *PredictOnDemandRequest, opts ...http.CallOption) (*Prediction, error) {
	var out Prediction
	pattern := "/api/analysis/predict"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAnalysisServicePredictOnDemand))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AnalysisServiceHTTPClientImpl) RunAnalysis(ctx context.Context, in *RunAnalysisRequest, opts ...http.CallOption) (*Task, error) {
	var out Task
	pattern := "/api/analysis/run"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAnalysisServiceRunAnalysis))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
