// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: quant/v1/crawler.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FetchDailyBarsRequest asks the crawler for cleaned OHLCV for one or more symbols.
type FetchDailyBarsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockCodes    []string               `protobuf:"bytes,1,rep,name=stock_codes,json=stockCodes,proto3" json:"stock_codes,omitempty"`
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchDailyBarsRequest) Reset() {
	*x = FetchDailyBarsRequest{}
	mi := &file_quant_v1_crawler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchDailyBarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchDailyBarsRequest) ProtoMessage() {}

func (x *FetchDailyBarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quant_v1_crawler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchDailyBarsRequest.ProtoReflect.Descriptor instead.
func (*FetchDailyBarsRequest) Descriptor() ([]byte, []int) {
	return file_quant_v1_crawler_proto_rawDescGZIP(), []int{0}
}

func (x *FetchDailyBarsRequest) GetStockCodes() []string {
	if x != nil {
		return x.StockCodes
	}
	return nil
}

func (x *FetchDailyBarsRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *FetchDailyBarsRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

// CleanedDailyBar is a single OHLCV row produced by the crawler (no DB writes).
type CleanedDailyBar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockCode     string                 `protobuf:"bytes,1,opt,name=stock_code,json=stockCode,proto3" json:"stock_code,omitempty"`
	Market        string                 `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	TradeDate     string                 `protobuf:"bytes,3,opt,name=trade_date,json=tradeDate,proto3" json:"trade_date,omitempty"`
	Open          float64                `protobuf:"fixed64,4,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,5,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,6,opt,name=low,proto3" json:"low,omitempty"`
	Close         float64                `protobuf:"fixed64,7,opt,name=close,proto3" json:"close,omitempty"`
	Volume        int64                  `protobuf:"varint,8,opt,name=volume,proto3" json:"volume,omitempty"`
	Source        string                 `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanedDailyBar) Reset() {
	*x = CleanedDailyBar{}
	mi := &file_quant_v1_crawler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanedDailyBar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanedDailyBar) ProtoMessage() {}

func (x *CleanedDailyBar) ProtoReflect() protoreflect.Message {
	mi := &file_quant_v1_crawler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanedDailyBar.ProtoReflect.Descriptor instead.
func (*CleanedDailyBar) Descriptor() ([]byte, []int) {
	return file_quant_v1_crawler_proto_rawDescGZIP(), []int{1}
}

func (x *CleanedDailyBar) GetStockCode() string {
	if x != nil {
		return x.StockCode
	}
	return ""
}

func (x *CleanedDailyBar) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *CleanedDailyBar) GetTradeDate() string {
	if x != nil {
		return x.TradeDate
	}
	return ""
}

func (x *CleanedDailyBar) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *CleanedDailyBar) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *CleanedDailyBar) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *CleanedDailyBar) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *CleanedDailyBar) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *CleanedDailyBar) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// FetchDailyBarsResponse is one message per stock (server-streaming).
type FetchDailyBarsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockCode     string                 `protobuf:"bytes,1,opt,name=stock_code,json=stockCode,proto3" json:"stock_code,omitempty"`
	Bars          []*CleanedDailyBar     `protobuf:"bytes,2,rep,name=bars,proto3" json:"bars,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchDailyBarsResponse) Reset() {
	*x = FetchDailyBarsResponse{}
	mi := &file_quant_v1_crawler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchDailyBarsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchDailyBarsResponse) ProtoMessage() {}

func (x *FetchDailyBarsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quant_v1_crawler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchDailyBarsResponse.ProtoReflect.Descriptor instead.
func (*FetchDailyBarsResponse) Descriptor() ([]byte, []int) {
	return file_quant_v1_crawler_proto_rawDescGZIP(), []int{2}
}

func (x *FetchDailyBarsResponse) GetStockCode() string {
	if x != nil {
		return x.StockCode
	}
	return ""
}

func (x *FetchDailyBarsResponse) GetBars() []*CleanedDailyBar {
	if x != nil {
		return x.Bars
	}
	return nil
}

func (x *FetchDailyBarsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_quant_v1_crawler_proto protoreflect.FileDescriptor

const file_quant_v1_crawler_proto_rawDesc = "" +
	"\n" +
	"\x16quant/v1/crawler.proto\x12\bquant.v1\"r\n" +
	"\x15FetchDailyBarsRequest\x12\x1f\n" +
	"\vstock_codes\x18\x01 \x03(\tR\n" +
	"stockCodes\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\"\xe7\x01\n" +
	"\x0fCleanedDailyBar\x12\x1d\n" +
	"\n" +
	"stock_code\x18\x01 \x01(\tR\tstockCode\x12\x16\n" +
	"\x06market\x18\x02 \x01(\tR\x06market\x12\x1d\n" +
	"\n" +
	"trade_date\x18\x03 \x01(\tR\ttradeDate\x12\x12\n" +
	"\x04open\x18\x04 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x05 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x06 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\a \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\b \x01(\x03R\x06volume\x12\x16\n" +
	"\x06source\x18\t \x01(\tR\x06source\"|\n" +
	"\x16FetchDailyBarsResponse\x12\x1d\n" +
	"\n" +
	"stock_code\x18\x01 \x01(\tR\tstockCode\x12-\n" +
	"\x04bars\x18\x02 \x03(\v2\x19.quant.v1.CleanedDailyBarR\x04bars\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2g\n" +
	"\x0eCrawlerService\x12U\n" +
	"\x0eFetchDailyBars\x12\x1f.quant.v1.FetchDailyBarsRequest\x1a .quant.v1.FetchDailyBarsResponse0\x01B\x93\x01\n" +
	"\fcom.quant.v1B\fCrawlerProtoP\x01Z4github.com/gsxhnd/guanlan/internal/proto/quant/v1;v1\xa2\x02\x03QXX\xaa\x02\bQuant.V1\xca\x02\bQuant\\V1\xe2\x02\x14Quant\\V1\\GPBMetadata\xea\x02\tQuant::V1b\x06proto3"

var (
	file_quant_v1_crawler_proto_rawDescOnce sync.Once
	file_quant_v1_crawler_proto_rawDescData []byte
)

func file_quant_v1_crawler_proto_rawDescGZIP() []byte {
	file_quant_v1_crawler_proto_rawDescOnce.Do(func() {
		file_quant_v1_crawler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_quant_v1_crawler_proto_rawDesc), len(file_quant_v1_crawler_proto_rawDesc)))
	})
	return file_quant_v1_crawler_proto_rawDescData
}

var file_quant_v1_crawler_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_quant_v1_crawler_proto_goTypes = []any{
	(*FetchDailyBarsRequest)(nil),  // 0: quant.v1.FetchDailyBarsRequest
	(*CleanedDailyBar)(nil),        // 1: quant.v1.CleanedDailyBar
	(*FetchDailyBarsResponse)(nil), // 2: quant.v1.FetchDailyBarsResponse
}
var file_quant_v1_crawler_proto_depIdxs = []int32{
	1, // 0: quant.v1.FetchDailyBarsResponse.bars:type_name -> quant.v1.CleanedDailyBar
	0, // 1: quant.v1.CrawlerService.FetchDailyBars:input_type -> quant.v1.FetchDailyBarsRequest
	2, // 2: quant.v1.CrawlerService.FetchDailyBars:output_type -> quant.v1.FetchDailyBarsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_quant_v1_crawler_proto_init() }
func file_quant_v1_crawler_proto_init() {
	if File_quant_v1_crawler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quant_v1_crawler_proto_rawDesc), len(file_quant_v1_crawler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_quant_v1_crawler_proto_goTypes,
		DependencyIndexes: file_quant_v1_crawler_proto_depIdxs,
		MessageInfos:      file_quant_v1_crawler_proto_msgTypes,
	}.Build()
	File_quant_v1_crawler_proto = out.File
	file_quant_v1_crawler_proto_goTypes = nil
	file_quant_v1_crawler_proto_depIdxs = nil
}
